/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    miracles: Miracle;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    miracles: MiraclesSelect<false> | MiraclesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    'home-page': HomePage;
    'manifesto-page': ManifestoPage;
    'credits-page': CreditsPage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'manifesto-page': ManifestoPageSelect<false> | ManifestoPageSelect<true>;
    'credits-page': CreditsPageSelect<false> | CreditsPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Editors, theologians, and curators with access to the Tantum Ergo studio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'theologian' | 'editor';
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Imagery, audio, and reference scans used across the Atlas, LMS, and editorial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Reverent, descriptive alt text — read aloud by screen readers.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer, archive, or rights holder.
   */
  attribution?: string | null;
  /**
   * Marks this asset as filler. Frontend renders a [Sample] badge when shown.
   */
  _isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sequence?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Editorial articles and meditations. Listed at /reading and /reading/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  subtitle?: string | null;
  /**
   * Short summary shown on the /reading index and the homepage editorial band.
   */
  excerpt?: string | null;
  hero?: {
    eyebrow?: string | null;
    image?: (number | null) | Media;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * URL fragment under /reading/.
   */
  slug: string;
  /**
   * Sort key for the /reading index. Set when ready to publish.
   */
  publishedAt?: string | null;
  /**
   * Marks this article as filler / placeholder for the content team.
   */
  _isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The Atlas corpus. Each miracle gets a pin on /atlas; the inPilgrimage flag promotes it to the curated scrolltelling chapters.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "miracles".
 */
export interface Miracle {
  id: number;
  title: string;
  /**
   * 1–2 sentences. Shown in the pin tooltip and the drawer header.
   */
  summary: string;
  narrative?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sources?:
    | {
        label: string;
        url?: string | null;
        attribution?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Reliquary images shown in the drawer carousel.
   */
  artwork?: (number | Media)[] | null;
  type: 'eucharistic' | 'marian' | 'healing' | 'stigmata' | 'incorruptible' | 'other';
  ecclesialStatus: 'approved' | 'recognised' | 'worthy-of-belief' | 'under-investigation' | 'not-constatat';
  /**
   * Human-readable place name, e.g. "Lanciano, Italy".
   */
  locationName: string;
  /**
   * Pin position. Payload stores [longitude, latitude] — the same order Mapbox expects.
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates: [number, number];
  /**
   * Year only (no month/day). Negative for BC.
   */
  yearOccurred: number;
  /**
   * Renders as "c. 700" instead of "700" when true.
   */
  dateApproximate?: boolean | null;
  approvalDate?: string | null;
  /**
   * e.g. "Bishop of Tours, 1574".
   */
  approvingAuthority?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * URL fragment for live preview (/atlas?focus={slug}).
   */
  slug: string;
  /**
   * Promotes this miracle into the curated pilgrimage scrolltelling on /atlas.
   */
  inPilgrimage?: boolean | null;
  /**
   * Chapter order in the pilgrimage. Only used when inPilgrimage is true.
   */
  pilgrimageOrder?: number | null;
  /**
   * Marks this miracle as filler. Frontend renders a [Sample] badge.
   */
  _isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'miracles';
        value: number | Miracle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  attribution?: T;
  _isSample?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sequence?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  excerpt?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        image?: T;
      };
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  slug?: T;
  publishedAt?: T;
  _isSample?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "miracles_select".
 */
export interface MiraclesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  narrative?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        attribution?: T;
        id?: T;
      };
  artwork?: T;
  type?: T;
  ecclesialStatus?: T;
  locationName?: T;
  coordinates?: T;
  yearOccurred?: T;
  dateApproximate?: T;
  approvalDate?: T;
  approvingAuthority?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  slug?: T;
  inPilgrimage?: T;
  pilgrimageOrder?: T;
  _isSample?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide chrome — title, tagline, footer copy, socials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteTitle: string;
  siteTagline?: string | null;
  /**
   * Long-form footer copy. Plain prose works fine here.
   */
  footerCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  socials?:
    | {
        platform: 'x' | 'instagram' | 'youtube' | 'email';
        url: string;
        id?: string | null;
      }[]
    | null;
  brand?: {
    /**
     * Optional custom logo. If unset, the chi-rho + wordmark default renders.
     */
    logo?: (number | null) | Media;
    /**
     * PNG, transparent background, 32×32 or 64×64.
     */
    faviconLight?: (number | null) | Media;
    /**
     * PNG, transparent background, for dark mode.
     */
    faviconDark?: (number | null) | Media;
  };
  /**
   * mapbox:// URL. Leave blank for default style. Used by /atlas (Plan 2).
   */
  mapboxStyle?: string | null;
  catechistRateLimit: {
    requestsPerHour: number;
    refusalMessage?: string | null;
  };
  /**
   * Hide [Sample] badges sitewide once content team is ready for launch.
   */
  showSampleBadges?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The public homepage at /. Hero, scroll-scrubbed manifesto sequence, three pillar plates, reading band — all in one place.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * First line of the headline (before the italicised word).
     */
    headlineLine1?: string | null;
    /**
     * The italicised middle word/phrase, rendered in rubric red.
     */
    headlineItalic?: string | null;
    /**
     * Final line of the headline.
     */
    headlineLine2?: string | null;
    subheadline?: string | null;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryHref?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryHref?: string | null;
    /**
     * Full-bleed background image for the hero section. Aspect 16:9 ideal. Mobile crops centre.
     */
    image?: (number | null) | Media;
  };
  manifestoSequence?: {
    /**
     * When off, the section is omitted from the homepage entirely.
     */
    enabled?: boolean | null;
    /**
     * 3–6 frames recommended. Order = scroll order.
     */
    frames?:
      | {
          eyebrow?: string | null;
          caption?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pillars?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    /**
     * Final word/phrase, rendered italic in rubric red.
     */
    headlineItalic?: string | null;
    atlas?: {
      title?: string | null;
      intent?: string | null;
      href?: string | null;
      /**
       * Background image for this pillar plate. Aspect 4:5 portrait.
       */
      image?: (number | null) | Media;
    };
    doctrine?: {
      title?: string | null;
      intent?: string | null;
      href?: string | null;
      /**
       * Background image for this pillar plate. Aspect 4:5 portrait.
       */
      image?: (number | null) | Media;
    };
    catechist?: {
      title?: string | null;
      intent?: string | null;
      href?: string | null;
      /**
       * Background image for this pillar plate. Aspect 4:5 portrait.
       */
      image?: (number | null) | Media;
    };
  };
  readingBand?: {
    eyebrow?: string | null;
    /**
     * Shown when no published Articles exist yet.
     */
    emptyMessage?: string | null;
    /**
     * How many recent articles to surface.
     */
    limit?: number | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /manifesto page — long-form vision essay.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-page".
 */
export interface ManifestoPage {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /credits page — sources, attributions, ecclesial review notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits-page".
 */
export interface CreditsPage {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteTagline?: T;
  footerCopy?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  brand?:
    | T
    | {
        logo?: T;
        faviconLight?: T;
        faviconDark?: T;
      };
  mapboxStyle?: T;
  catechistRateLimit?:
    | T
    | {
        requestsPerHour?: T;
        refusalMessage?: T;
      };
  showSampleBadges?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineItalic?: T;
        headlineLine2?: T;
        subheadline?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryHref?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryHref?: T;
        image?: T;
      };
  manifestoSequence?:
    | T
    | {
        enabled?: T;
        frames?:
          | T
          | {
              eyebrow?: T;
              caption?: T;
              image?: T;
              id?: T;
            };
      };
  pillars?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineItalic?: T;
        atlas?:
          | T
          | {
              title?: T;
              intent?: T;
              href?: T;
              image?: T;
            };
        doctrine?:
          | T
          | {
              title?: T;
              intent?: T;
              href?: T;
              image?: T;
            };
        catechist?:
          | T
          | {
              title?: T;
              intent?: T;
              href?: T;
              image?: T;
            };
      };
  readingBand?:
    | T
    | {
        eyebrow?: T;
        emptyMessage?: T;
        limit?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-page_select".
 */
export interface ManifestoPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits-page_select".
 */
export interface CreditsPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null)
      | ({
          relationTo: 'miracles';
          value: number | Miracle;
        } | null);
    global?: ('home-page' | 'manifesto-page' | 'credits-page') | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}